title: ""  # Esconde o texto no topo para mostrar só a logo
description: Conectando tecnologia ao seu negócio
baseurl: "" # No GitHub Pages, mantenha isso vazio
url: "https://goaguiar99.github.io"

theme: minima

plugins:
  - jekyll-feed

minima:
  include:
    - head-custom.html
